# Generated by Django 4.1 on 2022-08-27 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_1', models.CharField(max_length=200)),
                ('time_2', models.CharField(max_length=200)),
                ('estadio', models.TextField()),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_do_jogo', models.DateTimeField(blank=True, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
