# Generated by Django 4.1 on 2022-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_bolao', '0002_jogo_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='fase',
            field=models.CharField(blank=True, choices=[('grupos', 'Fase de Grupos'), ('oitavas', 'Oitavas de final'), ('quartas', 'Quartas de final'), ('semi', 'Semi Final'), ('final', 'Final')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='estadio',
            field=models.CharField(max_length=100),
        ),
    ]
