# Generated by Django 4.1 on 2022-08-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_bolao', '0004_estadio_alter_jogo_estadio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_time', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('tecnico', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_1', to='blog_bolao.time'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_2', to='blog_bolao.time'),
        ),
    ]
